### ISSUE TITLE
seadriver for windows fail:  get 'protol-version' from wrong address

### ISSUE THREAD

**Issue by enomlap** [haiwen/seadrive-gui#110]
platform: window7
seadriver version: 1.0.1
fileserver port: 58082
http server port: 58080
Seafile works fine, Seadriver can log in but will never perform next step.
look into seadrive.log found this:
-----------------------------------------------------------
```
[01/28/19 15:50:59] http-tx-mgr.c(685): libcurl failed to GET http://192.168.7.132:8082/protocol-version: Couldn't connect to server.
[01/28/19 15:51:00] http-tx-mgr.c(1285): Bad response code for GET http://192.168.7.132:58080/seafhttp/protocol-version: 404.
```
-------------------------------------------------------------------------
both connects were wrong:
1, 8082 should be 58082,
2, http://192.168.7.132:58080/seafhttp/protocol-version should be 'http://192.168.7.132:58082/protocol-version'

but can not find how to specify this url:port from the Seadriver gui.

**Comment by LoggeL** [comment]
Same here seems like it doesn't respect the fileserver port

**Comment by killing** [comment]
Such configuration is not supported. You can only either use 8082 port or nginx/apache with /seafhttp prefix.
