### ISSUE TITLE
unable to install Seadrive 1.0.3 on some windows computers

### ISSUE THREAD

**Issue by ydixt** [haiwen/seadrive-gui#117]
As described in issue #116, installing Seadrive 1.0.3 requires restart after running the executable (an error is shown on first install).

After restart, a window pops up asking to install Seadrive, and the installation succeeded on all my computers but one. On success a window "Installation complete pops up", on failure nothing is shown and Seadrive is still version 1.0.1.

Tested on multiple computers all running windows 1809, firewall disabled, and admin rights.

- Windows 1809
- Seadrive 1.0.3

**Comment by monkeydri** [comment]
Still same issue with seadrive 1.0.4 (updating from 1.0.3).

Can only be installed by uninstalling seadrive first.

**Comment by killing** [comment]
This is caused by the certificate of 1.0.1 is invalidated by Microsoft. User has to
