### ISSUE TITLE
Wrong library permissions

### ISSUE THREAD

**Issue by andreasley** [haiwen/seadrive-gui#119]
The Seafile Drive Client sometimes makes libraries read-only if:

- a user is in multiple groups that have access to that library
- one of the groups (the one with the latest timestamp?) is read-only

### Steps to reproduce

1. Create group `GroupA`
2. Create group `GroupB`
3. Make `User` a member of both groups
4. Create library `Test` 
5. Share library `Test` with `GroupA` (read-write)
6. Share library `Test` with `GroupB` (read-only)
7. Restart SeaDrive.app to make sure library permissions are up-to-date

### Expected behavior

`User` should have permission to write in library `Test`.

### Actual behavior

`User` does not have permission to write in library `Test`.

### Environment

- Seafile Server 6.3.4 CE
- Seafile Drive Client 1.0.3 running under macOS 10.14.4

**Comment by andreasley** [comment]
The problem still exists with Seafile Drive Client 1.0.4 and macOS 10.14.5.

Any chance to get this looked at?
This bug makes SeaDrive basically useless for our institution. :(

**Comment by freeplant** [comment]
The bug will be fixed in version 1.0.5.

**Comment by freeplant** [comment]
Version 1.0.5 is ready now.

**Comment by andreasley** [comment]
I can confirm that the bug seems to be fixed in 1.0.5.

However, existing caches have to be cleared to force SeaDrive.app to update the repository permissions, which can be done like this:

1. Quit SeaDrive.app
2. Execute the following command in Terminal: `rm -R ~/.seadrive/data` (replace with path to your selected Cache directory, if you have changed the default)
3. Start SeaDrive.app again

**Warning:** Only do this if you're sure that all local changes have been uploaded to the server! Additionally, all locally cached files will be deleted and have to be fetched from the server again.
