### ISSUE TITLE
Improve error messages (0x8007045D => no space left on device)

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#125]
When trying to copy to seadrive and no space left on device we can see error 0x8007045D (see https://github.com/haiwen/seafile/issues/1908) :

![bug-seadrive-sd-transfer](https://user-images.githubusercontent.com/18724661/56584560-44068800-65dc-11e9-81b1-f58f3096f491.png)

In `seafile.log` we can find the cause of the error

```
...
C:/Users/username/seadrive/data\file-cache\788520a8-60e4-4b19-b496-5a858c764478\file/path/file.ext: No space left on device.
```

The error shown should instead be "no space left on device" so user does not have to dive in the logs to find the root of the issue.

Windows 10 1809
Seadrive 1.0.3

**Comment by killing** [comment]
The error is displayed by Windows and we can't control it. But we can add a pop-up notification in such case.

**Comment by monkeydri** [comment]
Maybe seadrive could check for space left on the device where cache is located before trying to copy the file and prevent the paste operation if not enough space, so this cryptic error message is not displayed ?

**Comment by killing** [comment]
Unfortunately SeaDrive has no ability to know what's the total amount of files to be copied in. That's high level information not accessible from the driver layer. SeaDrive only sees low level operations like read/write a file.

**Comment by Daniel15** [comment]
> The error is displayed by Windows and we can't control it. 

Is there no way of throwing a different error code? I'm pretty sure regular NTFS or FAT drives show a "no space left on device" error rather than a generic error code.
