### ISSUE TITLE
seadrive.log file size grows indefinitely

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#127]
On several computers (mac, windows, linux) `seadrive.log` is huge (> 500MB), this will be a good idea to clear old entries or to set max file size. 

- Seadrive 1.0.3
- Seadrive server Pro 6.3.12
- MacOS 10.12
- Windows 1809
- Ubuntu 18.10

**Comment by killing** [comment]
We'll add this to development plan.
