### ISSUE TITLE
Unable to uninstall seadrive (1.0.3)

### ISSUE THREAD

**Issue by ydixt** [haiwen/seadrive-gui#129]
When trying to uninstall Seadrive from Control Panel > Apps it fails silently (app still listed ans still installed). On restart a window is shown :

![Capture2](https://user-images.githubusercontent.com/18724661/56869701-15394900-6a04-11e9-9fc6-87c5d9a1492d.PNG)

But it then fails silently, not showing "Uninstallation complete" (similarly to what it does on install, see issue #117).

In Windows Event Viewer (Windows Log > Application) the error shown is `Product: SeaDrive 1.0.3 -- Removal failed.`

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="MsiInstaller" />
		<EventID Qualifiers="0">11725</EventID>
		<Level>4</Level>
		<Task>0</Task>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2019-04-28T20:03:26.954990500Z" />
		<EventRecordID>14633</EventRecordID>
		<Channel>Application</Channel>
		<Computer>pc04</Computer>
		<Security UserID="S-1-5-21-3077412411-1731019303-1220571892-1006" />
	</System>
	<EventData>
		<Data>Product: SeaDrive 1.0.3 -- Removal failed.</Data>
		<Data>(NULL)</Data>
		<Data>(NULL)</Data>
		<Data>(NULL)</Data>
		<Data>(NULL)</Data>
		<Data>(NULL)</Data>
		<Data />
		<Binary>7B41434332453943362D424144342D343733302D383841442D4135413546343735373146447D</Binary>
	</EventData>
</Event>
```
![Capture](https://user-images.githubusercontent.com/18724661/56869827-25522800-6a06-11e9-8f0e-ec14df62f117.PNG)

- Windows 1809
- Seadrive 1.0.3

**Comment by monkeydri** [comment]
After running [Microsoft Program Uninstall Utility ](https://support.microsoft.com/en-us/mats/program_install_and_uninstall) on Seadrive and then trying again to uninstall from Control Panel it worked.

**Comment by killing** [comment]
This is possibly due to the certificate used for signing the SeaDrive client expired recently. Windows cannot uninstall a package without valid certificate.
