### ISSUE TITLE
1TB limit

### ISSUE THREAD

**Issue by NiklasGollenstede** [haiwen/seadrive-gui#13]
I've just set up a Seafile instance (6.0.7) on a 120GB SSD with a 4TB HDD for the data directory.
Now I wanted to use Seadrive to upload around 2TB of files, but got stuck at 1TB, because the virtual Seadrive drive is full. I couldn't find any setting to extend it.

Is there such a setting somewhere or is the 1TB value hard-coded?

**Comment by NiklasGollenstede** [comment]
It appears to me that there is some kind of logic that recognizes that the initial 1TB is almost used up and at some point extends the virtual size of the drive: when I checked it again (the next day or the day after) the size was some oddish 9.7TB or something, and later it increased even further.

this happend on two computers, each synchronizing with the same seafile instance and account. I can't really test this any further at the moment, because seadrive is currently completely broken foe that user (I think some data corruption on the server, seadrive keeps failing to fetch some lists). But that's not topic of this issue and if I'm unable to fix it I will open another one.

I guess that the only problem for this issue is that I should not have been able to actually hit the initial 1TB limit - it was increased to late.

**Comment by killing** [comment]
We've raised the virtual disk size to 100TB if it's unlimited on the server.
