### ISSUE TITLE
code error 36 while trying to copy files on mac

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#131]
most of the time when trying to copy large amount of files from SD card to seadrive.
works fine on windows or on another directory on mac (not on seadrive).

there is enough space left on device for cache folder.

- seadrive 1.0.4
- macOS 10.12
- seafile server Pro 6.3.12

**Comment by killing** [comment]
Do you get an error from Finder? Could you provide a screenshot?

**Comment by ydixt** [comment]
Yes this code error 36 comes from a Finder dialog. Will try to take screenshot + seadrive.log next time it happens
