### ISSUE TITLE
all files modified by one client appear on seafile with modified date "just now"

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#132]
The files from one client are not updated on the server (thus not visible by other clients).

The client Seadrive is correctly connected (already tried to stop it and relaunch it).

The modifications can be seen on the server side in history but there seems to be a time error which prevents the files to be updated on server. Indeed all the modifications are indicated with "just now" even if being logged in correct order in the timeline

![seafile-history](https://user-images.githubusercontent.com/18724661/57919943-2acebf80-789a-11e9-9aaa-087795ded487.png)

- seadrive 1.0.4
- windows 1809
- seafile server Pro 6.3.12

**Comment by killing** [comment]
If a modification appears in the history should have been updated to the server successfully. The time shown in the history is the local time of the client when it made that change. The time on the server may be different from the client, which causes this confusion.

To be sure whether the update is on the server, you can view the snapshot of the library on that modification history.

**Comment by ydixt** [comment]
Well the time on client was correctly set and same than on server.

After logging out, clearing the cache and re-logging the syncing was then working (with correct time shown). client machine was not restarted and time was not changed.

All previous changes (seen with "just now") were not synced to other clients so I had to manually change modification date of all those files to force re-sync them.
