### ISSUE TITLE
folders with space at the end (trailing space) created on mac are not visible on windows

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#133]
# STR

- create a directory with space at the end on mac, ex `TEST `
- go on a windows computer, and wait forever.

I cannot test the reverse because File Explorer automatically trims the folders.

- seadrive 1.0.4
- windows 1809/macos 10.12/10.13
- seafile server Pro 6.3.12

**Comment by killing** [comment]
This is a designed behavior. Windows doesn't support folder/file names with trailing spaces. So they won't be downloaded or displayed on Windows.

**Comment by ydixt** [comment]
Well it works with Dropbox and with NAS (Samba) so there must be a way to circumvent that.

I have no way to restrict users to add spaces at the end of folder names on mac (of course it only happens by mistake).

**Comment by killing** [comment]
As per Dropbox's docs it doesn't work either: https://help.dropbox.com/syncing-uploads/files-not-syncing Perhaps they've changed the behavior?

**Comment by ydixt** [comment]
I just re-tested it to make sure, macOS 10.13 dropbox v73.4.188, when folder is created with trailing space it is automatically trimmed.

I think they achieved that by  using deeper kernel implementation than Fuse (or dokan), see https://blogs.dropbox.com/tech/2016/05/going-deeper-with-project-infinite/

**Comment by ydixt** [comment]
On NAS (Samba) behaviour is different : folder created with trailing space on mac appears with a trailing dot instead (special character ``) on Windows.
