### ISSUE TITLE
upload/download of files really slow

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#134]
As described in #128 When a file is added to a synced library, it takes a while to appear on some mac clients machines, even for a small file of few KB (going out and back in the folder multiple times to trigger seadrive sync).

Upload/download speed (visible in Transfer progress in context menu if Seadrive tray icon) is 10 MB/s maximum, whereas it is 60MB/s on the other mac/windows machines.

When uploading/downloading from web UI it is much faster and similar to other machines.

Most importantly it did not use to be this way, new files appeared almost instantly few months ago. I wonder if it is related to the library size, it is now 18703 files / 1.3 TB.

- Seadrive 1.0.4
- Seadrive server Pro 6.3.12
- MacOS 10.12/13

**Comment by ydixt** [comment]
Ok I found something interesting : if the file is added on library root it appears (almost) instantly, but if created on a lib subfolder it takes ages (on one mac machine more than 5 minutes).

Again, bug happens only on several mac machine, on mine, newly created file in lib subfolder takes a bit longer to appear but it does after few seconds (again while testing I go in/out the folder to trigger the re-sync).

**Comment by killing** [comment]
I understand your issue now. It's not a bug, but deliberately designed to work this way. The client won't pull the update from the server unless the user is actively browsing around in the SeaDrive folders. It's a measure to prevent the client from sending too many useless requests to the server asking for updates. It only asks for that when the user seems to be interested in the SeaDrive at the moment.

**Comment by ydixt** [comment]
Once again I understand that syncing is only triggered after browsing in the directory where change has happened remotely. However on some computer it is really slow, up to 5 minutes to sync a 1KB file (sometimes file never appears...) whereas on other computer (same macOS and seadrive version) file appear almost instantly. There is definitely something going on, please help me solve this issue, it makes seadrive useless for us as we are not able to collaborate with all the computers and we will have to switch away from Seafile for our shared storage solution.

**Comment by killing** [comment]
Sometimes it's Finder not showing the new files. I've met a few such issues before. In the file system the files are present, but not shown in Finder. Can you check with the command line?

**Comment by didrip** [comment]
Issue persists with Seadrive 1.0.5.

> Can you check with the command line?

Sorry I forgot to reply. I did try to use Terminal (`ls`) to check if files where updated but they did not.
