### ISSUE TITLE
file preview on macOS (quicklook) not working after 1.0.5 update

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#139]
File preview using spacebar does not work when using new 1.0.5 seadrive, use to work fine on 1.0.4. File needs to be opened once for the preview to work.

This is probably due to the following change :

> 1.0.5 (2019/06/11)
> [...]
>    [Mac] Add Mac Finder preview plugin to prevent automatically downloading of files

source : https://manual.seafile.com/changelog/drive-client-changelog.html

This change does not seem to increase sync speed or fix issues (see issue #134) so can it be removed ?

seadrive 1.0.4
macOS mojave

**Comment by andreasley** [comment]
This seems to work with SeaDrive 1.0.7 on macOS 10.15 Catalina.

**Comment by didrip** [comment]
Does not work for .ai files (Illustrator) with Seadrive 1.0.8

- macOS 10.14.5
- macOS 10.14.6

Works with local files, files on Network share (smb://) and files on Synology drive
