### ISSUE TITLE
SeaDrive doesn't show groups name in folder "Shared with groups"

### ISSUE THREAD

**Issue by JeanLouPtflbx** [haiwen/seadrive-gui#142]
I'll be more pleasant to have groups name in the "Shared with groups" folder,
so we can easily find librarys and folder sorted by group. 
The web gui allows that, SeaDrive should do it.

**Comment by jacky35** [comment]
Yes, I too support this request.

**Comment by andreasley** [comment]
If this will be implemented, it should be optional. For our use case, nesting the libraries wouldn't be helpful at all.
