### ISSUE TITLE
SeaDrive 1.8 on Mac does not show librarys if launched when not conncted to the network

### ISSUE THREAD

**Issue by JeanLouPtflbx** [haiwen/seadrive-gui#154]
Tested on MacOS Mojave, in french env.
This does not happen with SeaDrive 1.7.

**Comment by killing** [comment]
Can you check ~/.seadrive/logs/seadrive.log?

**Comment by killing** [comment]
We've reproduced the issue. We'll fix it soon.

**Comment by JeanLouPtflbx** [comment]
Great news ! thanks you.
