### ISSUE TITLE
Client folder dates do not match server

### ISSUE THREAD

**Issue by aarononeal** [haiwen/seadrive-gui#164]
Folders viewed on the drive show created and modified dates of `01-01-1970` and `{time of sync}` instead of the actual dates as recorded on the server.

This breaks backup and diff calculations when using other tools to compare the drive contents.

Files generally have correct modified dates but created dates are also `01-01-1970`.

**Comment by killing** [comment]
This is a limitation by Seafile's data model. It's not easy to change.

**Comment by aarononeal** [comment]
It looks like the modified dates are correct on the server, though maybe create date isn’t stored. Is a partial fix possible?
