### ISSUE TITLE
Unable to move files when transfer in progress

### ISSUE THREAD

**Issue by aarononeal** [haiwen/seadrive-gui#169]
Attempting to move a file while a background transfer (like an upload) is in progress fails.

This is especially problematic for large files which may take time to complete.

I expected the move to be processed and the background transfer to continue or resume.

**Comment by killing** [comment]
If you move the file within the same library, it's handled as another upload operation. Only one upload operation can be in progress for each library. So it'll be handled after the current one is finished. If you move across libraries, it should be handled by sending a request to the server. So it's handled immediately.
