### ISSUE TITLE
Reboot on update

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seadrive-gui#18]
I just started the update from seadrive 0.5.0 to 0.5.1. In the update process my computer suddenly rebooted, after that it continued the installation.
Please - never ever reboot a machine without the users active approval.

__
edit: os is windows 10 64, 
if the updater doesn't trigger a reboot i guess it was a weird coincidence, please close this issue in this case

**Comment by 92lleo** [comment]
checked with 0.5.1 to 0.5.2 on multiple machines, no problems, closed

**Comment by 92lleo** [comment]
Updated from 0.9.3 to 0.9.4.
Restart again without warning or popup.

**Comment by freeplant** [comment]
It will be fixed in the next release.
