### ISSUE TITLE
Feature Request: implement SeaDrive like OneDrive

### ISSUE THREAD

**Issue by MBcom** [haiwen/seadrive-gui#21]
Can you add SeaDrive Folder to left explorerbar like OneDrive is placed. So you do not need to add new drive - just save SeaCloud user files e.g. in c:\users\{name}\SeaCloud or better let the user choose the file location (and install location). In attachment you find the registry values to add the SeaCloud folder like the OneDrive folder (the manual I found here: https://superuser.com/questions/883424/how-to-add-google-drive-to-the-windows-explorer-sidebar ) and a picture which shows what I mean.
![bild1](https://cloud.githubusercontent.com/assets/27956078/25349885/9ba33cea-2923-11e7-8ffa-b2efcea4a9a7.png)

seacloud.reg
-----------------------------------
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}]
@="SeaCloud"
"System.IsPinnedToNamespaceTree"=dword:00000001
"SortOrderIndex"=dword:00000042

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\InProcServer32]
@=hex(2):25,00,53,00,59,00,53,00,54,00,45,00,4D,00,52,00,4F,00,4F,00,54,00,\
25,00,5C,00,73,00,79,00,73,00,74,00,65,00,6D,00,33,00,32,00,5C,00,73,00,68,\
00,65,00,6C,00,6C,00,33,00,32,00,2E,00,64,00,6C,00,6C,00,00,00

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\ShellFolder]
"FolderValueFlags"=dword:00000028
"Attributes"=dword:f080004d

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}]
@="SeaCloud"
"System.IsPinnedToNamespaceTree"=dword:00000001
"SortOrderIndex"=dword:00000042

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\InProcServer32]
@=hex(2):25,00,53,00,59,00,53,00,54,00,45,00,4D,00,52,00,4F,00,4F,00,54,00,\
25,00,5C,00,73,00,79,00,73,00,74,00,65,00,6D,00,33,00,32,00,5C,00,73,00,68,\
00,65,00,6C,00,6C,00,33,00,32,00,2E,00,64,00,6C,00,6C,00,00,00

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\ShellFolder]
"FolderValueFlags"=dword:00000028
"Attributes"=dword:f080004d

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\DefaultIcon]
@="C:\\\\Program Files (x86)\\\\SeaDrive\\\\bin\\\\seadrive-gui.exe,0"

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\Instance]
"CLSID"="{0E5AAE11-A475-4c5b-AB00-C66DE400274E}"

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
"TargetFolderPath"="S:\\\\"

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel]
"{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}]
@="SeaCloud"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\DefaultIcon]
@="C:\\\\Program Files (x86)\\\\SeaDrive\\\\bin\\\\seadrive-gui.exe,0"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\Instance]
"CLSID"="{0E5AAE11-A475-4c5b-AB00-C66DE400274E}"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
"TargetFolderPath"="S:\\\\"
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoDrives"=dword:00040000

**Comment by killing** [comment]
Sorry but this is not how SeaDrive works. It's designed to be a virtual drive. So there will be a new drive added. I think you maybe confused by the concepts of file syncing and virtual drive?
