### ISSUE TITLE
Please package for Ubuntu 20.04

### ISSUE THREAD

**Issue by s1shed** [haiwen/seadrive-gui#215]
[Ubuntu 20.04 LTS](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes) was just released today. 

I've tried building version 2.0.1 of the SeaDrive client but it fails to run because of an incompatible seadrive-daemon.

**Comment by stroudmw** [comment]
The following packages have unmet dependencies:
 seadrive-daemon : Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by s1shed** [comment]
Packages are available in a new repo, documented at https://download.seafile.com/published/seafile-user-manual/drive_client/drive_client_for_linux.md
