### ISSUE TITLE
Open source daemon

### ISSUE THREAD

**Issue by s1shed** [haiwen/seadrive-gui#232]
In the issue at https://github.com/haiwen/seadrive-gui/issues/215 I requested a build of SeaDrive which is compatible with Ubuntu 20.04. 

In the meantime, please consider releasing the daemon as open source so that "the community" can build their own packages. I built packages of the most recent code when Ubuntu 20.04 was first released but it fails to run because of the missing daemon. The daemon which is compatible with Ubuntu 18.04 refuses to run because of dependency issues.

**Comment by killing** [comment]
We have such a plan to open source SeaDrive for Linux. Please wait for the news!

**Comment by killing** [comment]
https://github.com/haiwen/seadrive-fuse
