### ISSUE TITLE
unable to uninstall 2.0.3 windows

### ISSUE THREAD

**Issue by avelo** [haiwen/seadrive-gui#237]
Uninstalling the 2.0.3 app in windows 10, the Seadrive node was still there in the explorer.
I tried to remove it and I was only able to do that from registry, making the node dissapear,
but the link to network library is still under seafile_root dir, and have access to the server.

How to fully remove the seadrive configuration?. seafile dir with configuration was deleted, but network drive still connects

**Comment by killing** [comment]
This should have been fixed with 2.0.5 version. After uninstallation, the shortcut will be removed.
