### ISSUE TITLE
Memory leak in seadrive2.0.3(Windows)

### ISSUE THREAD

**Issue by yyjdelete** [haiwen/seadrive-gui#239]
Tested with 2.0.3 (beta), after opened for about 15 days, it use 1.8G memory(commited).

Not sure what is leak since seadrive is not open source, but maybe related to another side of the rpc.
https://github.com/haiwen/seadrive-gui/blob/108a245d382a3b4a85e9aedc2d9a91020273a242/src/rpc/transfer-progress.cpp#L24
Since I can see a huge number of string `downloading_files`, `downloaded_files`, `{"ret":{"uploaded_files":[],"uploading_files":[]}}`, something like an hashcode `00001E267433710` and some other unknown binary in memory dump.

**Comment by killing** [comment]
Thank you for reporting. We'll look into it. Do you still see the same issue with 2.0.5 version?

**Comment by yyjdelete** [comment]
@killing 
Seems not happen in 2.0.5, I will remember the memory usage now, and check again tomorrow.
