### ISSUE TITLE
UI really wonky on High DPI screens

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seadrive-gui#26]
On my high DPI screen the SeaDrive UI (especially the settings screen) is at best extremely wonky, at worst unreadable. It seems like the text scales fine, but the ui element spacings and window sizes don't. In the screenshot you can see that it seems to cut off a few options, making them inaccessible (I don't know which ones since I can't see them).
![seadrive_dpi](https://cloud.githubusercontent.com/assets/777285/26799905/a176aa64-4a37-11e7-9fa6-87e8aea838b7.PNG)

**Comment by freeplant** [comment]
It should have fixed in the latest version.
