### ISSUE TITLE
Compatibility with macOS Big Sur (macOS 11)

### ISSUE THREAD

**Issue by andreasley** [haiwen/seadrive-gui#260]
The bundled version of `osxfuse.fs` in SeaDrive for macOS is not compatible with the next major version, which will be released soon under the name "macOS Big Sur".
The latest release of osxfuse, version 3.11.2 (from https://github.com/osxfuse/osxfuse), works fine.

**Comment by killing** [comment]
We'll upgrade the the latest osxfuse version.

**Comment by andreasley** [comment]
Any idea when that might happen? macOS Big Sur will be released tomorrow and I'd like to tell my users when they can expect to be able to update. :)

**Comment by killing** [comment]
This is released today! Have a try.

**Comment by andreasley** [comment]
Works great; thank you!
