### ISSUE TITLE
Windows: Allow setting sync path

### ISSUE THREAD

**Issue by xobs** [haiwen/seadrive-gui#263]
The Seadrive client supports setting the path to the cache for syncing, however it does not allow setting the sync path on a per-server basis.

This became an issue for me when Seadrive decided that it would rename my cache from `D:\Cache\seadrive\Sean Cro` to `D:\Cache\seadrive\sean` and then to `D:\Cache\seadrive\Sean Cro_1`.

I have many symlinks that point to the old name, and it does not seem possible to change it back. Additionally, if I had any unsynced files in the previous path, those changes would be lost.

**Comment by killing** [comment]
This is a bug that has been fixed. Now it won't change your sync path.
For allowing setting sync path for different servers, we don't have plan to support that. We want to keep it simple.
