### ISSUE TITLE
Windows: Document how to remove duplicate SeaDrive entries

### ISSUE THREAD

**Issue by xobs** [haiwen/seadrive-gui#265]
SeaDrive has created three instances of `SeaDrive` on my machine. Only one of these is valid. SeaDrive should not do this (see #264), however there should be documentation on how to fix this when it happens.

SeaDrive v2.0.5

![image](https://user-images.githubusercontent.com/238325/98493298-142ddc80-2275-11eb-8a11-a5ac549bce82.png)

**Comment by killing** [comment]
Please refer to the last FAQ of this doc: https://download.seafile.com/published/seafile-user-manual/drive_client/drive_client_2.0_for_windows_10.md
