### ISSUE TITLE
[Windows] Nice name in notifications

### ISSUE THREAD

**Issue by johkoenig** [haiwen/seadrive-gui#268]
In notifications, the name of the program is noted as "seadrive-gui.exe". In my eyes, this is too technical. Something like "SeaDrive" would be more appropriate.
![nice-messages](https://user-images.githubusercontent.com/42836313/99156159-0508bd80-26bf-11eb-9819-b127c4d322db.png)

Best regards,
Joko

**Comment by killing** [comment]
We'll change the name.

**Comment by killing** [comment]
This is fixed in 2.0.12 version.
