### ISSUE TITLE
[Windows] Missing translation in context menu

### ISSUE THREAD

**Issue by johkoenig** [haiwen/seadrive-gui#269]
See screenshot below.
The context menu is missing the translation of "Always keep on this device" and "Free up space".
According to transifex, the German translation is complete and has no missing strings.

![missing-translation](https://user-images.githubusercontent.com/42836313/99156473-5e71ec00-26c1-11eb-8560-0a25cb2f2368.png)

**Comment by killing** [comment]
These two entries are added by Windows system, not SeaDrive. So it's possibly a system language issue. I've seen other German users have these two entries in German.
