### ISSUE TITLE
"Seadrive ejected unexpectedly" after waking from sleep

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seadrive-gui#27]
I'm using Seadrive 0.6.2 on Windows 10. I had my libraries mounted on drive S:\ with Seadrive and then put my computer into power saving (?) mode. After waking it, a Seadrive warning popped up that the "Seadrive was ejected unexpectedly". I don't know the exact wording since it's set to German for me. After that Seadrive wasn't running anymore, but I still had the virtual S:\ drive hanging around, that was empty when opening it. When restarting Seadrive, S:\ wasn't available anymore to choose as a drive letter.

Edit: Here's a screenshot of the error popup, as well as one of the drive list with the ejected drive (D:\ used to be the mounted Seadrive)

![seadrive_ausgeworfen](https://cloud.githubusercontent.com/assets/777285/26821672/78f7ec5e-4aa7-11e7-80a4-2b4fb5fc99a3.PNG)
![seadrive_leer](https://cloud.githubusercontent.com/assets/777285/26821674/7c53051e-4aa7-11e7-8097-1cd58406674c.PNG)

**Comment by 92lleo** [comment]
Had the same problem several times, but i cant't reproduce it now (0.6.2)

**Comment by killing** [comment]
It seems SeaDrive died unexpectedly. Can you post seadrive.log?

**Comment by Rojetto** [comment]
seadrive.log: https://pastebin.com/WKMebvMj
seadrive_gui.log: https://pastebin.com/ZKLfWa4f

Host and user name for the server were actually valid and not example.com.

These are the logs from today:
9:44 Booted PC
10:02 Put PC into hibernation to see if problem is reproducible
10:04 Wake PC again, Seadrive works but lost server connection, reestablishes it quickly
still 10:04 Lock PC
10:10 Unlock PC, Seadrive ejected unexpectedly

**Comment by wb7** [comment]
This is a "me too". Exactly the same log entries.

**Comment by killing** [comment]
From the log, it seems seadrive daemon was ejected/unmounted by the Dokany kernel driver or some third-party software. The daemon just exited "normally", not died. It could be an issue with the Dokany driver. We'll look into this.

**Comment by freeplant** [comment]
In version 0.8.0, SeaDrive will re-mount itself when it is unmounted after Windows sleep.
