### ISSUE TITLE
VLC Errors when trying to start uncached .mkv

### ISSUE THREAD

**Issue by denis-roy** [haiwen/seadrive-gui#29]
## VERSIONS
Seafile 6.0.9
Seadrive 0.7.0
VLC 2.2.6

## PROBLEM
When I double-click on an .mkv to open it with VLC, I seem to be getting a flurry of error messages (a good hundred of them) before the movie actually starts:
```
File reading failed:
VLC could not read the file (Bad file descriptor).
```

I know I can hide those with VLC but I was wondering if it wasn't an indicator of an issue on the way files are cached in Seadrive? Does it permits the app to load a file that is not entirely cached or some other way that lead VLC to print such errors?

**Comment by killing** [comment]
The drive client doesn't require the entire file to be cached before reading it. But sometimes the application can read faster or skip some part of the file. In that case and if the network is not fast enough, there may be read errors returned to application.

**Comment by denis-roy** [comment]
Thanks for your answer @killing

I've reopened this issue to suggest the addition of context menu items like "Cache this file" and "Cache this folder" when right-clicking on unsynched Seadrive items.

I believe it could help us avoid the above VLC errors and other read-ahead errors.

Thank you!
