### ISSUE TITLE
Why hide cache setting in Windows?

### ISSUE THREAD

**Issue by Chuanbin-Wang** [haiwen/seadrive-gui#290]
OS: Windows 10
SeaDrive: 2.0.12

I can't find the cache setting in setting dialog. And I see in source code, it's been hided. 
![image](https://user-images.githubusercontent.com/76732400/108299828-23a8b400-71da-11eb-999d-b47123d50c35.png)

Any body knows why hide it?

**Comment by killing** [comment]
2.0 version no longer needs to limit the cache size and clean the cache. See the doc: https://help.seafile.com/drive_client/drive_client_2.0_for_windows_10/
