### ISSUE TITLE
Update repository instruction for Ubuntu

### ISSUE THREAD

**Issue by paulocoghi** [haiwen/seadrive-gui#34]
The instructions to install Seafile Drive Client in Ubuntu are a little incorrect.

Since the repository server has only 64bit files, the command:

    echo deb http://deb.seadrive.org jessie main | sudo tee /etc/apt/sources.list.d/seafile.list

not only needs to replace `jessie` by `xenial`, but the line also needs a `[ arch=amd64 ]` after the `deb`.

So, the complete and correct line for Ubuntu is:

    echo deb [ arch=amd64 ] http://deb.seadrive.org xenial main | sudo tee /etc/apt/sources.list.d/seafile.list

With the current instructions, we receive the error bellow while attempting to update, and it isn't possible to install the drive client.

    E: Failed to fetch http://deb.seadrive.org/dists/xenial/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by lins05** [comment]
Emm, we provide both 64 and 32bit repos in the repo. I just tried to download it manually and it works:

```sh
curl -I http://deb.seadrive.org/dists/xenial/main/binary-i386/Packages
```

Maybe it's a CDN caching issue. I'll take a look later.

**Comment by paulocoghi** [comment]
Is everything correct in the file "http://deb.seadrive.org/dists/xenial/Release"?

I don't understand it well, but it seems to me that only 64bit is informed in the line 7 "Architecture"

**Comment by tmeissner** [comment]
I get the same error with a clean install of Xubuntu 16.04. The error disappears with the solution of @paulocoghi

**Comment by paulocoghi** [comment]
@lins05 , the address "http://deb.seadrive.org/dists/xenial/main/binary-i386/Packages" is available to curl it manually, but it inst' listed in "http://deb.seadrive.org/dists/xenial/Release" file.

That's it.

**Comment by egroeper** [comment]
@lins05 I can confirm this. The Release of xenial needs to be fixed. The Release file of jessie is correct.

You can simply compare both:
http://deb.seadrive.org/dists/xenial/Release
http://deb.seadrive.org/dists/jessie/Release

Please fix this.

**Comment by muellefr** [comment]
Appears to be fixed now.. can someone confirm?

**Comment by paulocoghi** [comment]
@muellefr , it is fixed now. Thanks, @lins05 !
