### ISSUE TITLE
Creating "System volumen information" folder

### ISSUE THREAD

**Issue by holantomas** [haiwen/seadrive-gui#35]
_SeaDrive Client 0.8.0 (**should do same in older versions**)_
_Windows 10_

System create on virtual disk(**S:/**) system folder "**System volume information**" which cause create same named library in seafile.

**Comment by 92lleo** [comment]
Same here on 0.8.0, windows 10. Seadroid keeps creating the Libary form System folder

**Comment by freeplant** [comment]
This is fixed in 0.8.1.
