### ISSUE TITLE
Drive Client for Windows 0.8.0 can't save MS office file

### ISSUE THREAD

**Issue by jaykinso** [haiwen/seadrive-gui#37]
Starting from updated win10 pro x64 16299

**Comment by killing** [comment]
Can you provide a screenshot of the error? And do you have any error messages in your seadrive.log?

**Comment by jaykinso** [comment]
![word](https://user-images.githubusercontent.com/33210783/32258307-c8f342a0-bef4-11e7-8338-8aa2654f7af3.png)
word和excel文档在seadrive的挂载盘中打开后无法保存，提示权限方面的问题，直接在挂载盘内新建、覆盖、剪切文件都是正常的，
 seadrive.log内看不出有什么错误，
试验了两台电脑都是win10更新至Build 16299后出现的这个问题
office试验了多个版本都是这个情况
Operating System: Windows 10 专业版 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)

**Comment by killing** [comment]
seadrive.log 日志里面有没有错误呢？

**Comment by jaykinso** [comment]
[seadrive.log.txt](https://github.com/haiwen/seadrive-gui/files/1436245/seadrive.log.txt)
seadrive.log 日志里面并没有查看到有何错误

**Comment by Evild67** [comment]
Same problem with win10 pro x64 16299

**Comment by freeplant** [comment]
Can you give the new 0.8.2 version a test?

**Comment by killing** [comment]
If it still fails, please upload or post seadrive.log here. There should be relevant log messages.

**Comment by jaykinso** [comment]
已经更新了0.8.2的挂载盘客户端，问题依旧。
请看log


[seadrive.log](https://github.com/haiwen/seadrive-gui/files/1460280/seadrive.log)

**Comment by freeplant** [comment]
A related issue: https://github.com/dokan-dev/dokany/issues/611

**Comment by freeplant** [comment]
It will be fixed in version 0.8.4.
