### ISSUE TITLE
SeaDrive drive failed to initialize

### ISSUE THREAD

**Issue by SPRINGJICHUN** [haiwen/seadrive-gui#4]
I don't know where I can get help, so I come here.
When SeaDrive installed successfully. Run it from the Desktop Icon, but show me SeaDrive drive failed to initialize.
不知道去哪里寻求帮助,所以就来到了这里.
当我在windows 10 周年版上安装好Windows 挂载盘客户端后,双击桌面上的客户端图标,提示我"SeaDrive drive failed to initialize",

**Comment by killing** [comment]
Have a look at seadrive-gui.log and seadrive.log. It's possible that the default drive letter is already used in your computer. You can choose another drive letter.

**Comment by SPRINGJICHUN** [comment]
The drive letter what I choose is S. I never use this letter before on my computer

When I run it, show me SeaDrive drive failed to initialize.

[cid:image001.png@01D23462.DEEC8E90]

The information in the seaDrive.log is:

[16/11/01 17:05:58] /C/dev/seafpkg/build/seadrive-msi-build/seadrive-gui-0.3.1/extensions/shell-ext.cpp(line 124) pathInRepo: getReposList returns false

I do not know where I can find seadrive-gui.log on my computer.

Think you!
