### ISSUE TITLE
Running Seadrive in Windows fails after re-Installation if drive letter is taken in the meantime

### ISSUE THREAD

**Issue by mathiasslawik** [haiwen/seadrive-gui#41]
When uninstalling Seadrive in Windows the settings are not fully removed from the registry, especially the drive letter (e.g., D:).

When re-installing seadrive at a later point when there actually is a new drive under the previous letter (e.g., D:) it cannot be run, complaining that Seadrive unexpectedly closed.

I've removed the settings from the registry and now it allows me to select a new drive letter and works as expected.

**Comment by PSOHart** [comment]
The folder to remove
HKEY_CURRENT_USER\Software\SeaDrive
