### ISSUE TITLE
IO Error - Opening PDF

### ISSUE THREAD

**Issue by holantomas** [haiwen/seadrive-gui#50]
Hi,
again is PDF error here on same computer. Seadrive have no sync errors, only Windows file explorer and Adobe reader freezy.

**seadrive.log**
```
[01/08/18 14:42:36] dokan-ops.c(2322): Failed to set file fbc79196-f109-4959-a23c-30d5eee65888/folder/subfolder/SUBFOLDER/subsubfolder/lastsubfolder hidden in repo tree.
[01/08/18 14:42:36] dokan-ops.c(63): SetFileAttributes \Firm\folder\subfolder\SUBFOLDER\subsubfolder\lastsubfolder: IO error
```

I can send you full logs (seadrive.log have 120MB) and PDF file but don't want make them public.

**Comment by freeplant** [comment]
Please upload the logs and the file to https://download.seafile.com/u/d/5cd866f6eb6741999afc/

Does the error occur every time for this file?

**Comment by holantomas** [comment]
@freeplant I don't think so. It's pretty much random and it left zombie adobe reader processes which have high CPU usage. I have to stop seadrive client and start it again. We talk about this in last issue and this problem was for some time.

Uploaded

**Comment by holantomas** [comment]
@freeplant @killing Did you found something?

**Comment by freeplant** [comment]
We haven't found much valuable information yet. This may be a kernel related problem. We don't have time to look into that way yet.

**Comment by holantomas** [comment]
OK, only I need is info cause management asking me how long :D
