### ISSUE TITLE
chmod +x in FUSE not working? expected behaviour?

### ISSUE THREAD

**Issue by labor4** [haiwen/seadrive-gui#52]
Is it expected behaviour that I cannot set the execution bit on FUSE'd seadrive?

I would find it useful to sync scripts and apps.

before: ls -l
`
-rw-r--r--  1 manu  staff  3 26 Jan 09:24 hello.sh
`

chmod
`
chmod +x hello.sh
`

after, the same: ls -l
`
-rw-r--r--  1 manu  staff  3 26 Jan 09:24 hello.sh
`

OS: High Sierra 10.13.2
Client: 0.8.5

best
manu

**Comment by freeplant** [comment]
+x is not supported.
