### ISSUE TITLE
Mount as regular harddrive or network drive

### ISSUE THREAD

**Issue by kocane** [haiwen/seadrive-gui#54]
Could a feature to mount the drive as something else than 'removable device' be implemented?

**Comment by freeplant** [comment]
Why do you need this feature?

**Comment by kocane** [comment]
@freeplant I just think it would be nice, especially to have it appear as a network drive, also for my parents as well. Removable drives are for USB drives etc

**Comment by kocane** [comment]
@freeplant another argument could be that seadrive pops up in various applications involving removable drives, e.g. preparing a usb with Rufus or the Windows Upgrader tool. Harmless, maybe, but not exactly optimal.
