### ISSUE TITLE
Login does not use the configured proxy server

### ISSUE THREAD

**Issue by jan-di** [haiwen/seadrive-gui#6]
When I try to login with a new account, the initial connection does not use the configured proxy server (to get the api2/token). After the succesfull login (via firewall-rule) the traffic runs properly over the proxy server.

------

Bei der Erstellung eines neuen Kontos wird während dem Loginvorgang nicht beachtet, ob bereits ein Proxy eingetragen wurde. Es wird unabhängig der Konfiguration versucht die Seite direkt anzusprechen (für den Sitzungstoken). Die eigentliche Traffic der Syncronisationsdaten wird anschließend problemlos an den Proxy Server weitergeleitet.

**Comment by lins05** [comment]
Should be fixed in https://github.com/haiwen/seadrive-gui/commit/afdc20d. We'll include it in the next release.
