### ISSUE TITLE
Seadrive is not mapped to unique user

### ISSUE THREAD

**Issue by jkaberg** [haiwen/seadrive-gui#7]
I'm using Windows 10.

When I map a drive to one user on my desktop (user X), and then sign in (switch user without sign out user X) as another user (user Y). User Y can then access and has full rights to user X drive

I haven't tested it the other way around, but I'm guessing that works to. 

What I expected:
That the drive is mapped only for the user account that created the drive

**Comment by kocane** [comment]
It works fine now but it's a bit annoying that when running programs as administrator, they cannot see the drive

**Comment by xdml** [comment]
On Windows (in my case Windows 10, 64 bit) it is not allowed to run seadrive by multiple users at same time.

Scenario: hotdesk with multiple user accounts using that computer. The first user who sign in, can start seadrive and map a letter. If user does not sign off, but new user sign in (for example from locked screen), than that user is not able to start seadrive (in my case with same letter mapping) with error message like "seadrive already running".

User is able to access someone else seadrive - SECURITY RISK.

Expected:
each user has own seadrive running with own mappings, even if multiple users use same drive letter.

**Comment by moobyfr** [comment]
What is the state of this security issue ? This is blocking us for enabling the use of seadrive for our students. And seafile itself isn't a issue because the students move between rooms, and it would take forever to resync always the libraries. 

Another issue is for RDS users, where all users see the mapped drive.

I had a look at ``dokany``there is a option available to map the drive for the current user only: ``DOKAN_OPTIONS``: ``DOKAN_OPTION_CURRENT_SESSION``, but not sure it's enough

**Comment by freeplant** [comment]
The current version `dokany` that SeaDrive used there is a bug that causing the SeaDrive be rejected after sleeping if `DOKAN_OPTION_CURRENT_SESSION` is used. We haven't tested the latest version of `dokany` yet.

**Comment by moobyfr** [comment]
I've found the issue on dokany, still open: https://github.com/dokan-dev/dokany/issues/634 (BTW 1.0.3 doesn't have the regression)

**Comment by satheras** [comment]
Maybe my mentioned issue is related to that one: https://github.com/haiwen/seadrive-gui/issues/79

I really would like to stress out that this issues should be dealt with top priority!

**Comment by freeplant** [comment]
In the latest version, there is an option to let the drive only be accessible by the current user.
