### ISSUE TITLE
client timeout too short

### ISSUE THREAD

**Issue by shoeper** [haiwen/seadrive-gui#80]
Because of this seadrive fails with very large libraries. See haiwen/seafile/issues/2084

**Comment by elcamlost** [comment]
I think. you can just cache some recent state of repo directories for big repos and answer on such requests very fast.

**Comment by bmatthias** [comment]
Same here. 
For large libraries, the client fails to download the index because of a timeout that is too short.
Timeout must be longer.

**Comment by killing** [comment]
Thanks for pointing out. I think the same optimization can be added as in the sync client.
