### ISSUE TITLE
Feature: Only mount certain libraries

### ISSUE THREAD

**Issue by Henrik0x7F** [haiwen/seadrive-gui#82]
I'm a happy Seafile user for over 2 years now. I use it for collaboration, download links and backups. The later of them kinda prevents me from using the drive client. I would love to mount the libraries I use for collaboration but have a bad feeling about mounting my backups. A feature to select which libraries are mounted would be a great addition in my opinion.

**Comment by toger5** [comment]
can u not just mount the whole seadrive, and than link only the needed folders to a good location like you home folder. (that is what i am currently doing)
Since seadrive is only caching whatever you use this should not be a problem
