### ISSUE TITLE
Can't start SeaDrive on MacOS since 0.9.4

### ISSUE THREAD

**Issue by captainark** [haiwen/seadrive-gui#86]
Hi,

I can't get SeaDrive to work on my Mac since the 0.9.4 release.

I'm getting the following error message :

![screenshot 2018-10-01 at 11 52 44](https://user-images.githubusercontent.com/6699651/46281956-8a2cc900-c570-11e8-9bde-d37d847e4b98.png)

In `~/.seadrive/logs/seadrive-gui.log`, I've notice that the following command is now issued when I start Seadrive :
```
[10/01/18 11:52:36] starting seadrive daemon: seadrive "-d" "/Users/captainark/.seadrive/data" "-l" "/Users/captainark/.seadrive/logs/seadrive.log" "-f" "/Users/captainark/SeaDrive" "-o" "volname=SeaDrive,noappledouble,allow_other,local"
```

When I try to run this command manually, I get the following message :
```
mount_osxfuse: failed to mount /Users/captainark/SeaDrive@/dev/osxfuse0: Operation not permitted
```

My user does not have administration rights on my machine, and the `allow_other` option of osxfuse requires elevated permissions.

0.9.3 works fine because the `"volname=SeaDrive,noappledouble"` options are used in this version.

Is the `allow_other` option necessary ? Is there a way for me to configure this behavior ?

Thanks.

**Comment by killing** [comment]
We'll improve this in later version.

**Comment by captainark** [comment]
Hi,

I have upgraded to Seadrive 1.0.0 and it is working fine on a user without administrative rights (the `-o volname=SeaDrive` option is used on startup).

This doesn't seem to have made it to the changelog, but thanks for the fix !
