### ISSUE TITLE
cannot install on ubuntu 18.04

### ISSUE THREAD

**Issue by monkeydri** [haiwen/seadrive-gui#91]
followed the instructions from https://www.seafile.com/en/help/drive_client_linux/ but could not install seadrive on ubuntu 18.04.

```
echo deb http://deb.seadrive.org jessie main | sudo tee /etc/apt/sources.list.d/seafile.list
sudo apt-get update
```

`sudo apt-get install seadrive-gui` =>

```
The following packages have unmet dependencies:
 seadrive-gui : Depends: seadrive-daemon (= 0.9.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Where `sudo apt-get install seadrive-daemon` =>
```
 seadrive-daemon : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
                   Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable
```

**Comment by monkeydri** [comment]
On ubuntu 18.04 libcurl4 is used hence the issue, it cannot be installed in parallel to libcurl3.

**Comment by killing** [comment]
Perhaps you should use 'bionic' instead of 'jessie', that's for Deiban 9, not Ubuntu 18.04.

**Comment by monkeydri** [comment]
yes thanks a lot : https://deb.seadrive.org/bionic/pool/main/s/seadrive-daemon/seadrive-daemon_0.9.5_amd64.deb

Then install seadrive-gui works like a charm.

**Comment by monkeydri** [comment]
```
echo deb http://deb.seadrive.org bionic main | sudo tee /etc/apt/sources.list.d/seafile.list
sudo apt-get update
sudo apt install seadrive-gui
```

`sudo apt-get install seadrive-gui`
