### ISSUE TITLE
Update Function not finding new version through GUI

### ISSUE THREAD

**Issue by satheras** [haiwen/seadrive-gui#98]
See the screenshot.

I have 0.9.5 installed under windows 10 and the Button for updates shows that there isnt a newer version. But we all know that version 1.0 is already released.

This also happened to me with a previous version. Therefore i had to download it manually from the website. I think there is a bug inside!

[https://imgur.com/a/4sBK8Vf](url)

**Comment by shoeper** [comment]
Upload images to github, please.

![eovjtyv](https://user-images.githubusercontent.com/5340585/49477669-e97fb180-f81d-11e8-9c91-eeac0ec33ffd.png)

**Comment by monkeydri** [comment]
I can confirm the issue on Seadrive 1.0.1 on windows 1809 and macos. Cannot confirm on linux because I cannot see the GUI at all (see issue #114).

- Seadrive 1.0.1
- Windows 1809
- macOS sierra

**Comment by monkeydri** [comment]
Still same bug on seadrive 1.0.3 (not finding version 1.0.4) on windows and macOS.

**Comment by didrip** [comment]
Still same bug on Seadrive 1.0.4 on Windows ans macOS (not finding version 1.0.5/6).
