### ISSUE TITLE
cannot stop notifcations

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#99]
despite unchecking "Notify when libraries are synchronized" in settings, I keep getting notifications from new files in libraries.

`seadrive-gui` `1.0.0`, `ubuntu` `18.10`, `nautilus` `3.26.4`.

*Note : this setting works well in `seafile-gui` (`6.1.5`).*

**Comment by monkeydri** [comment]
The application is not listed in Gnome notifications so there is no way to disable it.

This is due to missing entries in .desktop file, see here : https://www.reddit.com/r/gnome/comments/29w881/application_doesnt_appear_in_notification_settings/
